import { defineStore } from 'pinia'

export const useBigData = defineStore({
  id: 'bigData',
  state: () => ({
    cities: [
      { code: 1, name: 'Abbotabad' },
      { code: 2, name: 'Akora Khattak' },
      { code: 3, name: 'Alpuri' },
      { code: 4, name: 'Attock' },
      { code: 5, name: 'Bahawalpur' },
      { code: 6, name: 'Bairkot' },
      { code: 7, name: 'Bajur' },
      { code: 8, name: 'Bakhshali' },
      { code: 9, name: 'Balakot' },
      { code: 10, name: 'Bannu' },
      { code: 11, name: 'Bara' },
      { code: 12, name: 'Barawal Banda' },
      { code: 13, name: 'Batkhela' },
      { code: 14, name: 'Battagram' },
      { code: 15, name: 'Besham' },
      { code: 16, name: 'Booni' },
      { code: 17, name: 'Buner' },
      { code: 18, name: 'Burewala' },
      { code: 19, name: 'Chakdara' },
      { code: 20, name: 'Charbagh' },
      { code: 21, name: 'Charsadda' },
      { code: 22, name: 'Chicha Watni' },
      { code: 23, name: 'Chiniot' },
      { code: 24, name: 'Chitral' },
      { code: 25, name: 'D.I Khan' },
      { code: 26, name: 'Dagar' },
      { code: 27, name: 'Dara Adam Khel' },
      { code: 28, name: 'Dargai' },
      { code: 29, name: 'Darosh' },
      { code: 30, name: 'Daska' },
      { code: 31, name: 'DG Khan' },
      { code: 32, name: 'Dukki' },
      { code: 33, name: 'Faisalabad' },
      { code: 34, name: 'Ghalani' },
      { code: 35, name: 'Gilgit' },
      { code: 36, name: 'Gujar Khan' },
      { code: 37, name: 'Gujranwala' },
      { code: 38, name: 'Gujrat' },
      { code: 39, name: 'Hangu' },
      { code: 40, name: 'Haripur' },
      { code: 41, name: 'Hyderabad' },
      { code: 42, name: 'Islamabad' },
      { code: 43, name: 'Jahangira' },
      { code: 44, name: 'Jamrud' },
      { code: 45, name: 'Jhang' },
      { code: 46, name: 'Kalaya' },
      { code: 47, name: 'Kambat' },
      { code: 48, name: 'Karachi' },
      { code: 49, name: 'Karak' },
      { code: 50, name: 'Katlang' },
      { code: 51, name: 'Khaar' },
      { code: 52, name: 'Khanewal' },
      { code: 53, name: 'Khwaza Khela' },
      { code: 54, name: 'Kohat' },
      { code: 55, name: 'Kumbar' },
      { code: 56, name: 'Kuza Bandai' },
      { code: 57, name: 'Lachi' },
      { code: 58, name: 'Lahore' },
      { code: 59, name: 'Lakki Marwat' },
      { code: 60, name: 'Loralai' },
      { code: 61, name: 'Lundkhwar' },
      { code: 62, name: 'Madayn' },
      { code: 63, name: 'Maneeri Payan' },
      { code: 64, name: 'Manki Sharif' },
      { code: 65, name: 'Mansehra' },
      { code: 66, name: 'Mardan' },
      { code: 67, name: 'Matta' },
      { code: 68, name: 'Mattani' },
      { code: 69, name: 'Mian Channu' },
      { code: 70, name: 'Miranshah' },
      { code: 71, name: 'Mirpur' },
      { code: 72, name: 'Mongora' },
      { code: 73, name: 'Multan' },
      { code: 74, name: 'Munda' },
      { code: 75, name: 'Muzaffarabad' },
      { code: 76, name: 'Nowshera' },
      { code: 77, name: 'Nowshera' },
      { code: 78, name: 'Oghi' },
      { code: 79, name: 'Okara' },
      { code: 80, name: 'Pabbi' },
      { code: 81, name: 'Parachinar' },
      { code: 82, name: 'Peshawar' },
      { code: 83, name: 'Pishin' },
      { code: 84, name: 'Puran' },
      { code: 85, name: 'Quetta' },
      { code: 86, name: 'Rahim Yar Khan' },
      { code: 87, name: 'Rashakai' },
      { code: 88, name: 'Rawalpindi' },
      { code: 89, name: 'Rustam Mardan' },
      { code: 90, name: 'Sadda' },
      { code: 91, name: 'Sadiqabad' },
      { code: 92, name: 'Sahiwal' },
      { code: 93, name: 'Sakhakot' },
      { code: 94, name: 'Salehkhana' },
      { code: 95, name: 'Sarai Naurang' },
      { code: 96, name: 'Sargodha' },
      { code: 97, name: 'Shabqadar' },
      { code: 98, name: 'Shakardara' },
      { code: 99, name: 'Shergarh' },
      { code: 100, name: 'Sherkot' },
      { code: 101, name: 'Shewa Adda, Swabi' },
      { code: 102, name: 'Sialkot' },
      { code: 103, name: 'Sowari Buner' },
      { code: 104, name: 'Swabi' },
      { code: 105, name: 'Swat' },
      { code: 106, name: 'Takht Bhai' },
      { code: 107, name: 'Talash' },
      { code: 108, name: 'Tangi' },
      { code: 109, name: 'Tank' },
      { code: 110, name: 'Tehkal Payan' },
      { code: 111, name: 'Thall' },
      { code: 112, name: 'Thana' },
      { code: 113, name: 'Timergara' },
      { code: 114, name: 'Timergarha' },
      { code: 115, name: 'Topi' },
      { code: 116, name: 'Tordher' },
      { code: 117, name: 'Torghar' },
      { code: 118, name: 'Totalai' },
      { code: 119, name: 'Upper Dir' },
      { code: 120, name: 'Wana' },
      { code: 121, name: 'Wari' },
      { code: 122, name: 'Waziristan' },
      { code: 123, name: 'Zaida' },
      { code: 124, name: 'Zohb' }
    ],
    scenarios: [
      { code: 1, name: 'Digital Debit Card' },
      { code: 2, name: 'FEMPOWER Current Account' },
      { code: 3, name: 'FEMPOWER Savings Account' },
      { code: 4, name: 'Pay Plus Current Account' },
      { code: 5, name: 'Raast Current Account' },
      { code: 6, name: 'Raast Pay Plus Account' },
      { code: 7, name: 'Raast Savings Account' },
      { code: 8, name: 'Raast Tarseel Account' },
      { code: 9, name: 'Student Power Account' }
    ],
    branch_type: [
      { code: 1, name: 'Conventional' },
      { code: 2, name: 'Islamic Banking' }
    ],

    branches: [
      { code: 1, name: 'Main Branch' },
      { code: 2, name: 'University Road' },
      { code: 3, name: 'Kohat' },
      { code: 4, name: 'DIKhan' },
      { code: 7, name: 'Mardan' },
      { code: 10, name: 'GT Road' },
      { code: 11, name: 'Chitral' },
      { code: 12, name: 'Mingora' },
      { code: 13, name: 'Saddar Road' },
      { code: 14, name: 'Hattar' },
      { code: 15, name: 'Civil Secretariate' },
      { code: 16, name: 'Khyber Bazar Peshawar + LRH' },
      { code: 19, name: 'Haripur' },
      { code: 22, name: 'Islamabad' },
      { code: 23, name: 'M.M Alam Road' },
      { code: 24, name: 'Shahrah-e-Faisal' },
      { code: 25, name: 'Ashraf Road' },
      { code: 27, name: 'Muzaffarabad' },
      { code: 30, name: 'Rawalpindi' },
      { code: 31, name: 'Johar Town Lahore' },
      { code: 32, name: 'Sialkot' },
      { code: 33, name: 'Multan' },
      { code: 34, name: 'Shireen Jinnah Colony' },
      { code: 35, name: 'Mirpur' },
      { code: 36, name: 'Karachi Stock Exchange' },
      { code: 37, name: 'Gujrat' },
      { code: 38, name: 'Faisalabad-2' },
      { code: 39, name: 'Gujranwala' },
      { code: 40, name: 'Havelian' },
      { code: 41, name: 'Sargodha' },
      { code: 43, name: 'Abbottabad-2' },
      { code: 44, name: 'Chiniot Branch' },
      { code: 45, name: 'Sahiwal Branch' },
      { code: 46, name: 'Clifton Karachi' },
      { code: 47, name: 'Hyderabad' },
      { code: 48, name: 'High Court Branch Peshawar' },
      { code: 49, name: 'Karak' },
      { code: 50, name: 'Bahawalpur Branch' },
      { code: 51, name: 'Rahimyar Khan' },
      { code: 52, name: 'DHA Lahore' },
      { code: 53, name: 'Gilgit' },
      { code: 54, name: 'Sharah-e-Iqbal Quetta' },
      { code: 55, name: 'PWD Islamabad' },
      { code: 56, name: 'Dera Ghazi Khan' },
      { code: 57, name: 'Faysal Town Lahore' },
      { code: 59, name: 'Sadiqabad' },
      { code: 60, name: 'Khanewal' },
      { code: 61, name: 'Mian Channu' },
      { code: 62, name: 'Gujar Khan' },
      { code: 63, name: 'DHA Karachi' },
      { code: 65, name: 'Attock' },
      { code: 66, name: 'Warsak Road' },
      { code: 67, name: 'Bahadurabad Karachi' },
      { code: 68, name: 'Garrison Park' },
      { code: 69, name: 'Badami Bagh, Lahore' },
      { code: 70, name: 'Jhang' },
      { code: 71, name: 'Daska' },
      { code: 72, name: 'Napier Road, Karachi' },
      { code: 73, name: 'Dalazak Road' },
      { code: 74, name: 'Charsadda Road Peshawar' },
      { code: 75, name: 'Bannu' },
      { code: 76, name: 'Parachinar' },
      { code: 77, name: 'Yar Hussain' },
      { code: 78, name: 'Umarzai Branch, Charsadda' },
      { code: 79, name: 'Sheikh Maltoon Mardan' },
      { code: 80, name: 'Shergarh' },
      { code: 81, name: 'Katlang Branch Mardan' },
      { code: 82, name: 'Sherkot Kohat' },
      { code: 83, name: 'Hayatabad Phase-V Peshawar' },
      { code: 84, name: 'Chamkani' },
      { code: 85, name: 'Tordher, Swabi' },
      { code: 86, name: 'Darosh Chitral' },
      { code: 87, name: 'DI Khan, Sheikh Yusaf Adda' },
      { code: 88, name: 'Surdheri, Charsadda + Sub Branch' },
      { code: 89, name: 'Lundkhwar, Mardan' },
      { code: 91, name: 'Sadda, Kurram Agency' },
      { code: 92, name: 'Kohat Road, Peshawar' },
      { code: 93, name: 'Kuza Bandai, Swat' },
      { code: 96, name: 'Nasir Bagh Road Peshawar + RMT' },
      { code: 97, name: 'Haripur, Judicial Complex' },
      { code: 99, name: 'Angoor Adda, Waziristan' },
      { code: 302, name: 'Gomal University DI Khan' },
      { code: 303, name: 'KIMS+KDA Kohat' },
      { code: 304, name: 'F7, Islamabad' },
      { code: 305, name: 'Airport Road, Mingora, Swat' },
      { code: 306, name: 'Sher Shah Road, Nowshera' },
      { code: 307, name: 'Gur Mandi, Peshawar' },
      { code: 308, name: 'Maneeri Payan, Swabi' },
      { code: 309, name: 'I-9 Markaz, Islamabad' },
      { code: 310, name: 'Dabgari Garden, Peshawar' },
      { code: 311, name: 'Hamidaan Chowk, Karak' },
      { code: 312, name: 'Timergara' },
      { code: 313, name: 'Burrewala' },
      { code: 314, name: 'Chichawatni' },
      { code: 315, name: 'Azam Cloth Market, Lahore' },
      { code: 316, name: 'Thana, Malakand' },
      { code: 317, name: 'University of Peshawar' },
      { code: 318, name: 'Main Bazaar, Charsadda' },
      { code: 319, name: 'Besham' },
      { code: 320, name: 'Economic Zone, Nowshera' },
      { code: 321, name: 'Quetta, Double Road' },
      { code: 322, name: 'Phase-6, Hayatabad, Peshawar' },
      { code: 323, name: 'G-9 Islamabad' },
      { code: 324, name: 'I-8 Islamabad' },
      { code: 325, name: 'PIA Building Peshawar' },
      { code: 326, name: 'Top City Islamabad' },
      { code: 327, name: 'Allama Iqbal Town' },
      { code: 328, name: 'DHA Phase VI' },
      { code: 329, name: 'Model Town' },
      { code: 330, name: 'E-11 Islamabad' },
      { code: 331, name: 'DHA Phase-1 Islamabad' },
      { code: 332, name: 'Shakardara Kohat' },
      { code: 333, name: 'MMC Mardan' },
      { code: 5101, name: 'Karkhano Hayatabad' },
      { code: 5102, name: 'Jinnah Road Quetta' },
      { code: 5103, name: 'Bannu' },
      { code: 5104, name: 'Nowshera' },
      { code: 5105, name: 'Timergara' },
      { code: 5106, name: 'Tank' },
      { code: 5107, name: 'Hangu' },
      { code: 5108, name: 'Batkhela' },
      { code: 5109, name: 'S.I.T.E Karachi' },
      { code: 5110, name: 'Korangi Branch' },
      { code: 5111, name: 'Charsadda' },
      { code: 5113, name: 'Abbottabad' },
      { code: 5114, name: 'Garden town' },
      { code: 5115, name: 'Rawalpindi' },
      { code: 5116, name: 'Faisalabad' },
      { code: 5117, name: 'Mansehra' },
      { code: 5118, name: 'Swabi Branch' },
      { code: 5119, name: 'Peshawar City Asamai gate' },
      { code: 5121, name: 'KTH Peshawar' },
      { code: 5122, name: 'Mansehra2' },
      { code: 5123, name: 'Metroville' },
      { code: 5124, name: 'Shah Alam' },
      { code: 5125, name: 'Jamrud' },
      { code: 5126, name: 'Upper Dir' },
      { code: 5127, name: 'Sarai Naurang' },
      { code: 5128, name: 'Hayatabad Phase 3 Chowk' },
      { code: 5129, name: 'DI Khan Islamic' },
      { code: 5130, name: 'Thall' },
      { code: 5131, name: 'Sowari Buner' },
      { code: 5132, name: 'Mingora 2' },
      { code: 5133, name: 'F 10 Markaz' },
      { code: 5134, name: 'Battagram' },
      { code: 5135, name: 'Topi' },
      { code: 5136, name: 'Dargai' },
      { code: 5137, name: 'Chew Bazar Chitral' },
      { code: 5138, name: 'Kohat II' },
      { code: 5139, name: 'Khwaja Gunj Mardan' },
      { code: 5140, name: 'Okara' },
      { code: 5141, name: 'IBB Miran Shah' },
      { code: 5142, name: 'Vehari Road, Multan' },
      { code: 5143, name: 'Khwaza Khela' },
      { code: 5144, name: 'Kumbar' },
      { code: 5145, name: 'Shabqadar' },
      { code: 5146, name: 'Tarnol' },
      { code: 5147, name: 'Saleh Khana' },
      { code: 5148, name: 'Loralai' },
      { code: 5149, name: 'Chakdara, Lower Dir' },
      { code: 5150, name: 'Takht Bhai' },
      { code: 5151, name: 'Jehangira' },
      { code: 5152, name: 'IBB Wana' },
      { code: 5153, name: 'IBB Ghalani' },
      { code: 5154, name: 'City Circular Road, Peshawar' },
      { code: 5155, name: 'Ring Road, Peshawar' },
      { code: 5156, name: 'GulBahar Peshawar' },
      { code: 5157, name: 'Barikot Swat' },
      { code: 5158, name: 'Tangi' },
      { code: 5159, name: 'Pabbi Nowshera' },
      { code: 5160, name: 'Alpuri (Shangla)' },
      { code: 5161, name: 'Wari (Upper Dir)' },
      { code: 5162, name: 'Manki Sharif Nowshera' },
      { code: 5163, name: 'Khar Branch Bajaur Agency' },
      { code: 5164, name: 'Matta Swat' },
      { code: 5165, name: 'Torghar' },
      { code: 5166, name: 'Achini Payan Peshawar' },
      { code: 5167, name: 'Torkham / Landi Kotal' },
      { code: 5168, name: 'Shewa Adda' },
      { code: 5169, name: 'Munda Lower Dir' },
      { code: 5170, name: 'Kabal Swat' },
      { code: 5171, name: 'IBB Kalaya' },
      { code: 5172, name: 'Mall Road Peshawar' },
      { code: 5173, name: 'Lakki Marwat' },
      { code: 5174, name: 'Puran Shangla' },
      { code: 5175, name: 'Dara Adam Khel' },
      { code: 5176, name: 'Sakhakot' },
      { code: 5177, name: 'Zhob' },
      { code: 5178, name: 'Tehkal Payan' },
      { code: 5179, name: 'Sugar Mill Bypass Road' },
      { code: 5180, name: 'Bara Kahu' },
      { code: 5181, name: 'Charbagh Swat' },
      { code: 5182, name: 'Rashakai Nowshera' },
      { code: 5183, name: 'Rustam Mardan' },
      { code: 5184, name: 'Barawal Banda, upper Dir' },
      { code: 5185, name: 'HMC Peshawar' },
      { code: 5186, name: 'IBB Bara' },
      { code: 5187, name: 'Totalai, Buner' },
      { code: 5188, name: 'Madayn, Swat' },
      { code: 5189, name: 'Deewana Baba, Buner' },
      { code: 5190, name: 'Zaida, Swabi' },
      { code: 5191, name: 'IBB Mattani' },
      { code: 5192, name: 'Mandian, Abbotabad' },
      { code: 5193, name: 'Doaba, Hangu' },
      { code: 5194, name: 'Inayat Kallay, Bajaur' },
      { code: 5195, name: 'I-10 Markaz, Islamabad' },
      { code: 5196, name: 'Ghazi, Haripur' },
      { code: 5197, name: 'Balakot' },
      { code: 5198, name: 'IBB Haripur' },
      { code: 5199, name: 'Bakhshali, Mardan' },
      { code: 5200, name: 'Lachi, Kohat' },
      { code: 5201, name: 'Akora Khattak' },
      { code: 5202, name: 'Bacha Khan Medical Complex Swabi' },
      { code: 5203, name: 'Saidu Sharif Mingora, Swat' },
      { code: 5204, name: 'Pishin' },
      { code: 5205, name: 'KGN Hospital Bannu' },
      { code: 5206, name: 'Dukki' },
      { code: 5207, name: 'Pir Baba , Buner' },
      { code: 5208, name: 'Toor Warsak, Buner' },
      { code: 5209, name: 'Hayatabad PH-II, Peshawar' },
      { code: 5210, name: 'Kambat, Samar bagh' },
      { code: 5211, name: 'Phandu Chowk, Peshawar' },
      { code: 5212, name: 'MTI Qazi H. Ahmed Nowshera' },
      { code: 5213, name: 'Dagar' },
      { code: 5214, name: 'Booni Chitral' },
      { code: 5215, name: 'ASC Nowshera' },
      { code: 5216, name: 'Bahria Town Rawalpindi' },
      { code: 5217, name: 'Harichand Charsadda' },
      { code: 5218, name: 'Talash, Lower Dir' },
      { code: 5219, name: 'Bab-e-Khyber, Jamrud Bazar' },
      { code: 5220, name: 'Oghi' },
      { code: 5221, name: 'IBB Charsadda Road' },
      { code: 5222, name: 'GT Road, Timergara' },
      { code: 5223, name: 'IBB Blue Area Isb' },
      { code: 5225, name: 'Sunehri Masjid Road Branch' }
    ]
  }),
  actions: {}
})
