import { defineStore } from 'pinia'

export const useBigData = defineStore({
  id: 'bigData',
  state: () => ({
    cities: [
        { "code": 1, "name": "Abbotabad" },
        { "code": 2, "name": "Akora Khattak" },
        { "code": 3, "name": "Alpuri" },
        { "code": 4, "name": "Attock" },
        { "code": 5, "name": "Bahawalpur" },
        { "code": 6, "name": "Bairkot" },
        { "code": 7, "name": "Bajur" },
        { "code": 8, "name": "Bakhshali" },
        { "code": 9, "name": "Balakot" },
        { "code": 10, "name": "Bannu" },
        { "code": 11, "name": "Bara" },
        { "code": 12, "name": "Barawal Banda" },
        { "code": 13, "name": "Batkhela" },
        { "code": 14, "name": "Battagram" },
        { "code": 15, "name": "Besham" },
        { "code": 16, "name": "Booni" },
        { "code": 17, "name": "Buner" },
        { "code": 18, "name": "Burewala" },
        { "code": 19, "name": "Chakdara" },
        { "code": 20, "name": "Charbagh" },
        { "code": 21, "name": "Charsadda" },
        { "code": 22, "name": "Chicha Watni" },
        { "code": 23, "name": "Chiniot" },
        { "code": 24, "name": "Chitral" },
        { "code": 25, "name": "D.I Khan" },
        { "code": 26, "name": "Dagar" },
        { "code": 27, "name": "Dara Adam Khel" },
        { "code": 28, "name": "Dargai" },
        { "code": 29, "name": "Darosh" },
        { "code": 30, "name": "Daska" },
        { "code": 31, "name": "DG Khan" },
        { "code": 32, "name": "Dukki" },
        { "code": 33, "name": "Faisalabad" },
        { "code": 34, "name": "Ghalani" },
        { "code": 35, "name": "Gilgit" },
        { "code": 36, "name": "Gujar Khan" },
        { "code": 37, "name": "Gujranwala" },
        { "code": 38, "name": "Gujrat" },
        { "code": 39, "name": "Hangu" },
        { "code": 40, "name": "Haripur" },
        { "code": 41, "name": "Hyderabad" },
        { "code": 42, "name": "Islamabad" },
        { "code": 43, "name": "Jahangira" },
        { "code": 44, "name": "Jamrud" },
        { "code": 45, "name": "Jhang" },
        { "code": 46, "name": "Kalaya" },
        { "code": 47, "name": "Kambat" },
        { "code": 48, "name": "Karachi" },
        { "code": 49, "name": "Karak" },
        { "code": 50, "name": "Katlang" },
        { "code": 51, "name": "Khaar" },
        { "code": 52, "name": "Khanewal" },
        { "code": 53, "name": "Khwaza Khela" },
        { "code": 54, "name": "Kohat" },
        { "code": 55, "name": "Kumbar" },
        { "code": 56, "name": "Kuza Bandai" },
        { "code": 57, "name": "Lachi" },
        { "code": 58, "name": "Lahore" },
        { "code": 59, "name": "Lakki Marwat" },
        { "code": 60, "name": "Loralai" },
        { "code": 61, "name": "Lundkhwar" },
        { "code": 62, "name": "Madayn" },
        { "code": 63, "name": "Maneeri Payan" },
        { "code": 64, "name": "Manki Sharif" },
        { "code": 65, "name": "Mansehra" },
        { "code": 66, "name": "Mardan" },
        { "code": 67, "name": "Matta" },
        { "code": 68, "name": "Mattani" },
        { "code": 69, "name": "Mian Channu" },
        { "code": 70, "name": "Miranshah" },
        { "code": 71, "name": "Mirpur" },
        { "code": 72, "name": "Mongora" },
        { "code": 73, "name": "Multan" },
        { "code": 74, "name": "Munda" },
        { "code": 75, "name": "Muzaffarabad" },
        { "code": 76, "name": "Nowshera" },
        { "code": 77, "name": "Nowshera" },
        { "code": 78, "name": "Oghi" },
        { "code": 79, "name": "Okara" },
        { "code": 80, "name": "Pabbi" },
        { "code": 81, "name": "Parachinar" },
        { "code": 82, "name": "Peshawar" },
        { "code": 83, "name": "Pishin" },
        { "code": 84, "name": "Puran" },
        { "code": 85, "name": "Quetta" },
        { "code": 86, "name": "Rahim Yar Khan" },
        { "code": 87, "name": "Rashakai" },
        { "code": 88, "name": "Rawalpindi" },
        { "code": 89, "name": "Rustam Mardan" },
        { "code": 90, "name": "Sadda" },
        { "code": 91, "name": "Sadiqabad" },
        { "code": 92, "name": "Sahiwal" },
        { "code": 93, "name": "Sakhakot" },
        { "code": 94, "name": "Salehkhana" },
        { "code": 95, "name": "Sarai Naurang" },
        { "code": 96, "name": "Sargodha" },
        { "code": 97, "name": "Shabqadar" },
        { "code": 98, "name": "Shakardara" },
        { "code": 99, "name": "Shergarh" },
        { "code": 100, "name": "Sherkot" },
        { "code": 101, "name": "Shewa Adda, Swabi" },
        { "code": 102, "name": "Sialkot" },
        { "code": 103, "name": "Sowari Buner" },
        { "code": 104, "name": "Swabi" },
        { "code": 105, "name": "Swat" },
        { "code": 106, "name": "Takht Bhai" },
        { "code": 107, "name": "Talash" },
        { "code": 108, "name": "Tangi" },
        { "code": 109, "name": "Tank" },
        { "code": 110, "name": "Tehkal Payan" },
        { "code": 111, "name": "Thall" },
        { "code": 112, "name": "Thana" },
        { "code": 113, "name": "Timergara" },
        { "code": 114, "name": "Timergarha" },
        { "code": 115, "name": "Topi" },
        { "code": 116, "name": "Tordher" },
        { "code": 117, "name": "Torghar" },
        { "code": 118, "name": "Totalai" },
        { "code": 119, "name": "Upper Dir" },
        { "code": 120, "name": "Wana" },
        { "code": 121, "name": "Wari" },
        { "code": 122, "name": "Waziristan" },
        { "code": 123, "name": "Zaida" },
        { "code": 124, "name": "Zohb" }
    ],
    scenarios: [
        { "code": 1, "name": "Digital Debit Card" },
        { "code": 2, "name": "FEMPOWER Current Account" },
        { "code": 3, "name": "FEMPOWER Savings Account" },
        { "code": 4, "name": "Pay Plus Current Account" },
        { "code": 5, "name": "Raast Current Account" },
        { "code": 6, "name": "Raast Pay Plus Account" },
        { "code": 7, "name": "Raast Savings Account" },
        { "code": 8, "name": "Raast Tarseel Account" },
        { "code": 9, "name": "Student Power Account" }
    ],
    branch_type:[
        { "code": 1, "name": "Conventional" },
        { "code": 2, "name": "Islamic Banking" },
    ]
  }),
  actions: {
   
  }
})
